// Generated by gencpp from file motor_ctl/vel.msg
// DO NOT EDIT!


#ifndef MOTOR_CTL_MESSAGE_VEL_H
#define MOTOR_CTL_MESSAGE_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_ctl
{
template <class ContainerAllocator>
struct vel_
{
  typedef vel_<ContainerAllocator> Type;

  vel_()
    : lv(0.0)
    , rv(0.0)  {
    }
  vel_(const ContainerAllocator& _alloc)
    : lv(0.0)
    , rv(0.0)  {
  (void)_alloc;
    }



   typedef float _lv_type;
  _lv_type lv;

   typedef float _rv_type;
  _rv_type rv;





  typedef boost::shared_ptr< ::motor_ctl::vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_ctl::vel_<ContainerAllocator> const> ConstPtr;

}; // struct vel_

typedef ::motor_ctl::vel_<std::allocator<void> > vel;

typedef boost::shared_ptr< ::motor_ctl::vel > velPtr;
typedef boost::shared_ptr< ::motor_ctl::vel const> velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_ctl::vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_ctl::vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_ctl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_ctl': ['/home/corobot/catkin_ws/src/motor_ctl/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_ctl::vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_ctl::vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_ctl::vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_ctl::vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_ctl::vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_ctl::vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_ctl::vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f2d9a30844403ccb0451dd87e709319";
  }

  static const char* value(const ::motor_ctl::vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f2d9a30844403ccULL;
  static const uint64_t static_value2 = 0xb0451dd87e709319ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_ctl::vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_ctl/vel";
  }

  static const char* value(const ::motor_ctl::vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_ctl::vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 lv\n\
float32 rv\n\
";
  }

  static const char* value(const ::motor_ctl::vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_ctl::vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lv);
      stream.next(m.rv);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_ctl::vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_ctl::vel_<ContainerAllocator>& v)
  {
    s << indent << "lv: ";
    Printer<float>::stream(s, indent + "  ", v.lv);
    s << indent << "rv: ";
    Printer<float>::stream(s, indent + "  ", v.rv);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CTL_MESSAGE_VEL_H
